### ISSUE TITLE
typos in "Image" section

### ISSUE THREAD

**Issue by bwitka** [learn-co-curriculum/fe-getting-to-know-html#2]
The original text from the README is included below. The first word, "Imahe," should be "Image" and "allows" is misspelled in the last sentence (it appears as "aloows").

Imahe elements <img> allow us to link to an image and display it in the browser. The src attribute is where we provide the path to our image file. The alt attribute is where we provide alternate text for the visually impaired. Also good for search engines. The title attribute aloows us to type a phrase that will appear of the user hovers of the image for a period of time.

**Comment by AnnJohn** [comment]
thanks, we updated this.
